// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4WfEyTiPtIVvUlluIJCDKnR--4cqYnHQ',
    appId: '1:131678932416:web:acaca2929d7f53be5c0c25',
    messagingSenderId: '131678932416',
    projectId: 'cimera-75548',
    authDomain: 'cimera-75548.firebaseapp.com',
    storageBucket: 'cimera-75548.firebasestorage.app',
    measurementId: 'G-C0RH32C1J8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7D634aWmFEajWEBQQBSxNwV1_aGLBnkA',
    appId: '1:131678932416:android:6aa6ffc62fb9c52a5c0c25',
    messagingSenderId: '131678932416',
    projectId: 'cimera-75548',
    storageBucket: 'cimera-75548.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMpisC6law5Y1_U5u-6nwt2MoWbV3Zpfs',
    appId: '1:131678932416:ios:6296c38665729dff5c0c25',
    messagingSenderId: '131678932416',
    projectId: 'cimera-75548',
    storageBucket: 'cimera-75548.firebasestorage.app',
    iosBundleId: 'cimera.com.hello',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBMpisC6law5Y1_U5u-6nwt2MoWbV3Zpfs',
    appId: '1:131678932416:ios:6296c38665729dff5c0c25',
    messagingSenderId: '131678932416',
    projectId: 'cimera-75548',
    storageBucket: 'cimera-75548.firebasestorage.app',
    iosBundleId: 'cimera.com.hello',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB4WfEyTiPtIVvUlluIJCDKnR--4cqYnHQ',
    appId: '1:131678932416:web:06ac796c98892a545c0c25',
    messagingSenderId: '131678932416',
    projectId: 'cimera-75548',
    authDomain: 'cimera-75548.firebaseapp.com',
    storageBucket: 'cimera-75548.firebasestorage.app',
    measurementId: 'G-RMWVR7B11V',
  );
}
